### ISSUE TITLE
Precipitation

### ISSUE THREAD

**Issue by dianaveronez** [dianaveronez/Diana_CLIM680_Assig2#2]
1. Check the colors on the map.
2. Check the unit data.
3. Update colorbar to have more colors to show.

**Comment by Prukutu** [comment]
1. your colormap is not great because you are computing the range of values from the entire dataset but only showing a smaller section of it. You should play around with your actual values.
2. Yes, please check the units and label them correctly on the map. Also, the values are quite small, you can likely do a unit conversion that involves fewer zeros.
3. I think your number of colors is good.

**Comment by dianaveronez** [comment]
[Assig_clim680-DV-V2.zip](https://github.com/user-attachments/files/17806460/Assig_clim680-DV-V2.zip)

**Comment by Prukutu** [comment]
Hello Diana, 

I received an updated file for your homework but there is still the issue of the color range. It seems that in your domain, values range from ~0.0 mm to ~0.5 mm. I would play around with clev values around that.

**Comment by dianaveronez** [comment]
Hello Professor,
I had inserted a new file for assignment 2, however, I deleted this one because I saw a line to be improved. I'm sorry.
I'll insert the new version again.

**Comment by dianaveronez** [comment]
Hello Professor,
I updated the Homework 2 file.

**Comment by Prukutu** [comment]
Great!Can now close this issue.
